-- BODYBUILDING - LEGS & GLUTES
INSERT INTO exercise_library (name, category, muscle_group, is_default) VALUES
('Barbell back squat', 'bodybuilding', 'Legs & Glutes', true),
('Front squat', 'bodybuilding', 'Legs & Glutes', true),
('Sumo squat', 'bodybuilding', 'Legs & Glutes', true),
('Smith machine squat', 'bodybuilding', 'Legs & Glutes', true),
('Hack squat', 'bodybuilding', 'Legs & Glutes', true),
('Bulgarian split squat', 'bodybuilding', 'Legs & Glutes', true),
('Goblet squat (kettlebell squat)', 'bodybuilding', 'Legs & Glutes', true),
('Step-up', 'bodybuilding', 'Legs & Glutes', true),
('Forward lunge', 'bodybuilding', 'Legs & Glutes', true),
('Walking lunge', 'bodybuilding', 'Legs & Glutes', true),
('Romanian deadlift', 'bodybuilding', 'Legs & Glutes', true),
('Sumo deadlift', 'bodybuilding', 'Legs & Glutes', true),
('Conventional deadlift', 'bodybuilding', 'Legs & Glutes', true),
('Stiff-leg deadlift (barbell)', 'bodybuilding', 'Legs & Glutes', true),
('Stiff-leg deadlift (dumbbell)', 'bodybuilding', 'Legs & Glutes', true),
('Hip thrust', 'bodybuilding', 'Legs & Glutes', true),
('Single-leg hip bridge', 'bodybuilding', 'Legs & Glutes', true),
('Leg extension', 'bodybuilding', 'Legs & Glutes', true),
('Seated leg curl', 'bodybuilding', 'Legs & Glutes', true),
('Lying leg curl', 'bodybuilding', 'Legs & Glutes', true),
('Seated abductor machine', 'bodybuilding', 'Legs & Glutes', true),
('Seated adductor machine', 'bodybuilding', 'Legs & Glutes', true),
('45° leg press', 'bodybuilding', 'Legs & Glutes', true),
('Horizontal leg press', 'bodybuilding', 'Legs & Glutes', true),
('Unilateral leg press', 'bodybuilding', 'Legs & Glutes', true),
('Cable donkey kick', 'bodybuilding', 'Legs & Glutes', true),
('Glute kickback (on all fours)', 'bodybuilding', 'Legs & Glutes', true),
('Banded glute bridge', 'bodybuilding', 'Legs & Glutes', true),
('Lateral step-up', 'bodybuilding', 'Legs & Glutes', true),
('Cable hip extension', 'bodybuilding', 'Legs & Glutes', true),
('Banded squat', 'bodybuilding', 'Legs & Glutes', true),
('Sissy squat', 'bodybuilding', 'Legs & Glutes', true),
('Jefferson squat', 'bodybuilding', 'Legs & Glutes', true),
('Reverse hack squat', 'bodybuilding', 'Legs & Glutes', true),
('Split squat', 'bodybuilding', 'Legs & Glutes', true),
('Box squat', 'bodybuilding', 'Legs & Glutes', true),
('Zercher squat', 'bodybuilding', 'Legs & Glutes', true),
('Bulgarian squat', 'bodybuilding', 'Legs & Glutes', true),
('Jump squat', 'bodybuilding', 'Legs & Glutes', true),
('Single-leg deadlift', 'bodybuilding', 'Legs & Glutes', true),
('Unilateral leg curl', 'bodybuilding', 'Legs & Glutes', true),
('Isometric wall squat', 'bodybuilding', 'Legs & Glutes', true),
('Hex-bar stiff deadlift', 'bodybuilding', 'Legs & Glutes', true),
('Sumo squat with dumbbell', 'bodybuilding', 'Legs & Glutes', true),
('Smith machine lunge', 'bodybuilding', 'Legs & Glutes', true),
('Unilateral hack machine', 'bodybuilding', 'Legs & Glutes', true),
('Banded hip abduction', 'bodybuilding', 'Legs & Glutes', true),
('Pause squat', 'bodybuilding', 'Legs & Glutes', true),
('Weighted step-up', 'bodybuilding', 'Legs & Glutes', true),
('Tempo squat', 'bodybuilding', 'Legs & Glutes', true);

-- BODYBUILDING - CHEST
INSERT INTO exercise_library (name, category, muscle_group, is_default) VALUES
('Flat barbell bench press', 'bodybuilding', 'Chest', true),
('Flat dumbbell bench press', 'bodybuilding', 'Chest', true),
('Incline barbell bench press', 'bodybuilding', 'Chest', true),
('Incline dumbbell bench press', 'bodybuilding', 'Chest', true),
('Decline bench press', 'bodybuilding', 'Chest', true),
('Flat dumbbell fly', 'bodybuilding', 'Chest', true),
('Incline dumbbell fly', 'bodybuilding', 'Chest', true),
('Decline dumbbell fly', 'bodybuilding', 'Chest', true),
('High cable crossover', 'bodybuilding', 'Chest', true),
('Low cable crossover', 'bodybuilding', 'Chest', true),
('Pec deck (machine fly)', 'bodybuilding', 'Chest', true),
('Push-up', 'bodybuilding', 'Chest', true),
('Close-grip push-up', 'bodybuilding', 'Chest', true),
('Decline push-up', 'bodybuilding', 'Chest', true),
('Incline push-up', 'bodybuilding', 'Chest', true),
('Clap push-up', 'bodybuilding', 'Chest', true),
('Resistance band push-up', 'bodybuilding', 'Chest', true),
('Close-grip bench press', 'bodybuilding', 'Chest', true),
('Wide-grip bench press', 'bodybuilding', 'Chest', true),
('Alternating dumbbell bench press', 'bodybuilding', 'Chest', true),
('Unilateral bench press', 'bodybuilding', 'Chest', true),
('Dumbbell pullover', 'bodybuilding', 'Chest', true),
('Smith machine bench press', 'bodybuilding', 'Chest', true),
('Elevated push-up', 'bodybuilding', 'Chest', true),
('Cable bench press', 'bodybuilding', 'Chest', true),
('Cable fly', 'bodybuilding', 'Chest', true),
('Plyometric push-up', 'bodybuilding', 'Chest', true),
('Isometric bench press', 'bodybuilding', 'Chest', true),
('Push-up on plates', 'bodybuilding', 'Chest', true),
('Converging chest press machine', 'bodybuilding', 'Chest', true),
('Diverging chest press machine', 'bodybuilding', 'Chest', true),
('Bench press with chains', 'bodybuilding', 'Chest', true),
('Banded chest fly', 'bodybuilding', 'Chest', true),
('Incline fly', 'bodybuilding', 'Chest', true),
('Explosive push-up', 'bodybuilding', 'Chest', true),
('Floor press', 'bodybuilding', 'Chest', true),
('Diamond push-up', 'bodybuilding', 'Chest', true),
('Pause bench press', 'bodybuilding', 'Chest', true),
('Alternating push-up', 'bodybuilding', 'Chest', true),
('Banded bench press', 'bodybuilding', 'Chest', true),
('Neutral-grip bench press', 'bodybuilding', 'Chest', true),
('Unilateral cable fly', 'bodybuilding', 'Chest', true),
('Decline dumbbell press', 'bodybuilding', 'Chest', true),
('Ring push-up', 'bodybuilding', 'Chest', true),
('Medicine ball push-up', 'bodybuilding', 'Chest', true),
('Partial isometric press', 'bodybuilding', 'Chest', true),
('TRX chest fly', 'bodybuilding', 'Chest', true),
('Kettlebell push-up', 'bodybuilding', 'Chest', true),
('Military push-up', 'bodybuilding', 'Chest', true),
('Multipower bench press', 'bodybuilding', 'Chest', true);

-- CROSSFIT - LEGS & GLUTES
INSERT INTO exercise_library (name, category, muscle_group, is_default) VALUES
('Air squat', 'crossfit', 'Legs & Glutes', true),
('Front squat (CF)', 'crossfit', 'Legs & Glutes', true),
('Back squat (CF)', 'crossfit', 'Legs & Glutes', true),
('Overhead squat', 'crossfit', 'Legs & Glutes', true),
('Goblet squat (CF)', 'crossfit', 'Legs & Glutes', true),
('Thruster', 'crossfit', 'Legs & Glutes', true),
('Box jump', 'crossfit', 'Legs & Glutes', true),
('Jumping lunge', 'crossfit', 'Legs & Glutes', true),
('Pistol squat', 'crossfit', 'Legs & Glutes', true),
('Wall ball', 'crossfit', 'Legs & Glutes', true),
('Power clean', 'crossfit', 'Legs & Glutes', true),
('Hang clean', 'crossfit', 'Legs & Glutes', true),
('Squat clean', 'crossfit', 'Legs & Glutes', true),
('Clean & jerk', 'crossfit', 'Legs & Glutes', true),
('Power snatch', 'crossfit', 'Legs & Glutes', true),
('Hang snatch', 'crossfit', 'Legs & Glutes', true),
('Overhead lunge', 'crossfit', 'Legs & Glutes', true),
('Weighted step-up (CF)', 'crossfit', 'Legs & Glutes', true),
('Dumbbell thruster', 'crossfit', 'Legs & Glutes', true),
('Dumbbell clean', 'crossfit', 'Legs & Glutes', true),
('Kettlebell swing', 'crossfit', 'Legs & Glutes', true),
('Kettlebell snatch', 'crossfit', 'Legs & Glutes', true),
('Sumo deadlift high pull', 'crossfit', 'Legs & Glutes', true),
('Farmer''s carry', 'crossfit', 'Legs & Glutes', true),
('Overhead carry', 'crossfit', 'Legs & Glutes', true),
('Sandbag clean', 'crossfit', 'Legs & Glutes', true),
('Sandbag squat', 'crossfit', 'Legs & Glutes', true),
('Tire flip', 'crossfit', 'Legs & Glutes', true),
('Yoke carry', 'crossfit', 'Legs & Glutes', true),
('Wall sit', 'crossfit', 'Legs & Glutes', true),
('Jump squat (CF)', 'crossfit', 'Legs & Glutes', true),
('Burpee box jump', 'crossfit', 'Legs & Glutes', true),
('Weighted lunge', 'crossfit', 'Legs & Glutes', true),
('Sled push', 'crossfit', 'Legs & Glutes', true),
('Sled drag', 'crossfit', 'Legs & Glutes', true),
('Broad jump', 'crossfit', 'Legs & Glutes', true),
('Step-over', 'crossfit', 'Legs & Glutes', true),
('Weighted box step-up', 'crossfit', 'Legs & Glutes', true),
('Dumbbell snatch', 'crossfit', 'Legs & Glutes', true),
('Power jerk', 'crossfit', 'Legs & Glutes', true),
('Split jerk', 'crossfit', 'Legs & Glutes', true),
('Wall walk', 'crossfit', 'Legs & Glutes', true),
('Dumbbell lunge', 'crossfit', 'Legs & Glutes', true),
('Reverse lunge', 'crossfit', 'Legs & Glutes', true),
('Goblet lunge', 'crossfit', 'Legs & Glutes', true),
('Overhead step-up', 'crossfit', 'Legs & Glutes', true),
('Kettlebell goblet squat', 'crossfit', 'Legs & Glutes', true),
('Clean pull', 'crossfit', 'Legs & Glutes', true),
('Jump rope + squat combo', 'crossfit', 'Legs & Glutes', true),
('Weighted wall ball', 'crossfit', 'Legs & Glutes', true);

-- CROSSFIT - CHEST / SHOULDERS / CORE
INSERT INTO exercise_library (name, category, muscle_group, is_default) VALUES
('Push press', 'crossfit', 'Chest / Shoulders / Core', true),
('Strict press', 'crossfit', 'Chest / Shoulders / Core', true),
('Handstand push-up', 'crossfit', 'Chest / Shoulders / Core', true),
('Shoulder to overhead', 'crossfit', 'Chest / Shoulders / Core', true),
('Dumbbell press (CF)', 'crossfit', 'Chest / Shoulders / Core', true),
('Plate press', 'crossfit', 'Chest / Shoulders / Core', true),
('Arnold press', 'crossfit', 'Chest / Shoulders / Core', true),
('Turkish get-up', 'crossfit', 'Chest / Shoulders / Core', true),
('Handstand walk', 'crossfit', 'Chest / Shoulders / Core', true),
('Ring dip', 'crossfit', 'Chest / Shoulders / Core', true),
('Bar dip', 'crossfit', 'Chest / Shoulders / Core', true),
('Muscle-up', 'crossfit', 'Chest / Shoulders / Core', true),
('Toes-to-bar', 'crossfit', 'Chest / Shoulders / Core', true),
('Knees-to-elbows', 'crossfit', 'Chest / Shoulders / Core', true),
('Sit-up', 'crossfit', 'Chest / Shoulders / Core', true),
('V-up', 'crossfit', 'Chest / Shoulders / Core', true),
('L-sit', 'crossfit', 'Chest / Shoulders / Core', true),
('Hollow hold', 'crossfit', 'Chest / Shoulders / Core', true),
('GHD sit-up', 'crossfit', 'Chest / Shoulders / Core', true),
('Russian twist', 'crossfit', 'Chest / Shoulders / Core', true),
('Ab rollout', 'crossfit', 'Chest / Shoulders / Core', true),
('Side plank', 'crossfit', 'Chest / Shoulders / Core', true),
('Plank shoulder tap', 'crossfit', 'Chest / Shoulders / Core', true),
('Superman hold', 'crossfit', 'Chest / Shoulders / Core', true),
('Bird dog', 'crossfit', 'Chest / Shoulders / Core', true),
('Dragon flag', 'crossfit', 'Chest / Shoulders / Core', true),
('Windshield wiper', 'crossfit', 'Chest / Shoulders / Core', true),
('Reverse crunch', 'crossfit', 'Chest / Shoulders / Core', true),
('Weighted sit-up', 'crossfit', 'Chest / Shoulders / Core', true),
('Flutter kicks', 'crossfit', 'Chest / Shoulders / Core', true),
('Mountain climber', 'crossfit', 'Chest / Shoulders / Core', true),
('Hanging leg raise', 'crossfit', 'Chest / Shoulders / Core', true),
('Hanging knee raise', 'crossfit', 'Chest / Shoulders / Core', true),
('Toes-to-rings', 'crossfit', 'Chest / Shoulders / Core', true),
('Burpee', 'crossfit', 'Chest / Shoulders / Core', true),
('Burpee box jump-over', 'crossfit', 'Chest / Shoulders / Core', true),
('Devil''s press', 'crossfit', 'Chest / Shoulders / Core', true),
('Dumbbell snatch + burpee', 'crossfit', 'Chest / Shoulders / Core', true),
('Double unders (jump rope)', 'crossfit', 'Chest / Shoulders / Core', true),
('Rope climb', 'crossfit', 'Chest / Shoulders / Core', true),
('Assault bike sprint', 'crossfit', 'Chest / Shoulders / Core', true),
('Ski erg', 'crossfit', 'Chest / Shoulders / Core', true),
('Row erg', 'crossfit', 'Chest / Shoulders / Core', true),
('Box jump-over', 'crossfit', 'Chest / Shoulders / Core', true),
('Wall climb', 'crossfit', 'Chest / Shoulders / Core', true),
('Weighted plank', 'crossfit', 'Chest / Shoulders / Core', true),
('Barbell rollout', 'crossfit', 'Chest / Shoulders / Core', true),
('Farmer''s hold', 'crossfit', 'Chest / Shoulders / Core', true),
('Overhead kettlebell walk', 'crossfit', 'Chest / Shoulders / Core', true),
('Hand-release push-up', 'crossfit', 'Chest / Shoulders / Core', true);