// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwonynqoybfvaleyfmog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3b255bnFveWJmdmFsZXlmbW9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDMxMTIsImV4cCI6MjA3MTI3OTExMn0.Y8OvWIvi-i7Scb1RtZ1YG99MdYyu_7MD-dkcHZF3NGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});